name: Setup
description: Sets up the workflow
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          system-features = big-parallel
          accept-flake-config = true
    - name: Use Cachix store
        uses: cachix/cachix-action@v15
        with:
          name: copilot
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: copilot,nix-community
    - run: nix develop --impure --command just install
      shell: bash
